-- --------------------------------------------------------
-- Hôte:                         127.0.0.1
-- Version du serveur:           5.7.33 - MySQL Community Server (GPL)
-- SE du serveur:                Win64
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Listage de la structure de la base pour blog
CREATE DATABASE IF NOT EXISTS `blog` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `blog`;

-- Listage de la structure de la table blog. category
CREATE TABLE IF NOT EXISTS `category` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=latin1;

-- Listage des données de la table blog.category : ~25 rows (environ)
/*!40000 ALTER TABLE `category` DISABLE KEYS */;
INSERT INTO `category` (`id`, `name`, `slug`) VALUES
	(15, 'cat12', 'cat-12'),
	(16, 'cat13', 'cat-13'),
	(17, 'cat14', 'cat-14'),
	(18, 'cat15', 'cat-15'),
	(19, 'cat16', 'cat-16'),
	(20, 'cat17', 'cat-17'),
	(21, 'cat18', 'cat-18'),
	(22, 'cat19', 'cat-19'),
	(23, 'cat20', 'cat-20'),
	(24, 'cat21', 'cat-21'),
	(25, 'cat22', 'cat-22'),
	(26, 'cat23', 'cat-23'),
	(27, 'cat24', 'cat-24'),
	(28, 'cat25', 'cat-25');
/*!40000 ALTER TABLE `category` ENABLE KEYS */;

-- Listage de la structure de la table blog. post
CREATE TABLE IF NOT EXISTS `post` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `content` mediumtext NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=318 DEFAULT CHARSET=latin1;

-- Listage des données de la table blog.post : ~44 rows (environ)
/*!40000 ALTER TABLE `post` DISABLE KEYS */;
INSERT INTO `post` (`id`, `name`, `slug`, `content`, `created_at`) VALUES
	(295, 'post27', 'post-27', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2013-04-23 12:41:57'),
	(297, 'post29', 'post-29', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2011-05-26 06:19:25'),
	(298, 'post30', 'post-30', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2011-04-08 17:59:40'),
	(299, 'post31', 'post-31', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2016-11-07 15:45:24'),
	(300, 'post32', 'post-32', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2015-08-08 02:22:20'),
	(301, 'post33', 'post-33', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2011-05-29 04:43:01'),
	(303, 'post35', 'post-35', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2016-04-05 17:05:44'),
	(304, 'post36', 'post-36', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2014-02-07 10:24:24'),
	(305, 'post37', 'post-37', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2011-08-21 13:29:34'),
	(306, 'post38', 'post-38', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2010-04-28 05:15:19'),
	(307, 'post39', 'post-39', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2019-05-16 03:33:31'),
	(308, 'post40', 'post-40', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2018-07-04 11:17:15'),
	(309, 'post41', 'post-41', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2015-03-29 11:53:21'),
	(310, 'post42', 'post-42', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2013-06-28 01:11:09'),
	(311, 'post43', 'post-43', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2013-01-16 06:59:45'),
	(312, 'post44', 'post-44', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2014-07-23 20:53:40'),
	(313, 'post45', 'post-45', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2017-09-20 12:58:32'),
	(314, 'post46', 'post-46', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2013-03-22 22:18:41'),
	(315, 'post47', 'post-47', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2018-07-05 14:49:17'),
	(316, 'post48', 'post-48', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2017-05-26 14:54:21'),
	(317, 'post49', 'post-49', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et ullamcorper sem. Curabitur vel varius magna. Sed a nunc hendrerit, ultricies lorem sit amet, auctor eros. Fusce pharetra sit amet purus id euismod. Donec ultricies diam ut iaculis luctus. Integer sed augue nisi. Sed id dapibus nulla. Sed porta nisl tellus, non imperdiet mi molestie id. Vivamus finibus felis ut dolor cursus, eget rutrum nisl suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc aliquam, quam nec accumsan tincidunt, urna ipsum lacinia turpis, eget porttitor turpis sem at quam. Proin tincidunt commodo nisl, a varius nunc elementum eget.\r\n\r\n        Donec at convallis mauris, vitae lacinia nisi. Nunc lectus eros, tristique in pellentesque quis, suscipit id mauris. In a ullamcorper sapien. Vivamus quis dignissim augue. Phasellus euismod aliquam leo, vitae commodo lorem congue porta. Cras condimentum, est quis lacinia lobortis, erat metus malesuada mauris, sed dignissim arcu ex in velit. Sed non quam arcu. Nam non velit leo. Morbi bibendum massa in magna sagittis, eu fermentum nulla efficitur. In auctor aliquam nulla, id auctor magna cursus eget. Vestibulum dapibus varius tortor semper rhoncus.\r\n        \r\n        Fusce ut enim laoreet ipsum aliquet ultrices ac imperdiet ipsum. Donec tincidunt tristique porttitor. Aliquam erat volutpat. Sed dapibus, neque ac vulputate faucibus, nulla lorem viverra dolor, a dapibus nunc libero eget metus. Etiam nec varius orci, eu tincidunt turpis. Nullam tincidunt ex arcu, ut molestie nibh molestie quis. In congue efficitur tristique. Sed molestie at dolor eleifend pulvinar. Phasellus commodo orci eu diam commodo lobortis. Duis et porta ante, quis gravida justo. Nulla leo nisi, condimentum porttitor sollicitudin vel, mattis porttitor dui. Duis viverra maximus libero, et mattis lacus luctus at. Vivamus eget aliquet dui, sed congue dui. Mauris pretium ac purus vel elementum. Aliquam nec eros ut purus euismod imperdiet. ', '2014-11-15 19:01:47');
/*!40000 ALTER TABLE `post` ENABLE KEYS */;

-- Listage de la structure de la table blog. post_category
CREATE TABLE IF NOT EXISTS `post_category` (
  `post_id` int(10) unsigned NOT NULL,
  `category_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`post_id`,`category_id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_post` FOREIGN KEY (`post_id`) REFERENCES `post` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Listage des données de la table blog.post_category : ~44 rows (environ)
/*!40000 ALTER TABLE `post_category` DISABLE KEYS */;
INSERT INTO `post_category` (`post_id`, `category_id`) VALUES
	(309, 16),
	(317, 18),
	(300, 20),
	(304, 20),
	(298, 21),
	(306, 21),
	(311, 22),
	(295, 23),
	(303, 23),
	(307, 23),
	(315, 24),
	(314, 27);
/*!40000 ALTER TABLE `post_category` ENABLE KEYS */;

-- Listage de la structure de la table blog. user
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `isAdmin` tinyint(1) NOT NULL,
  `password_reset_date` date DEFAULT NULL,
  `password_reset_token` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Listage des données de la table blog.user : ~1 rows (environ)
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
INSERT INTO `user` (`id`, `username`, `email`, `password`, `isAdmin`, `password_reset_date`, `password_reset_token`) VALUES
	(1, 'admin', 'ulysse.valdenairepro@gmail.Com', 'a94a8fe5ccb19ba61c4c0873d391e987982fbbd3', 1, '2022-04-06', 'qTgMLahJfUSpH20mIWcF');
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
